# Generated by Django 2.2.6 on 2019-11-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peteleco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='send_email',
            field=models.BooleanField(default=False, verbose_name='Email enviado'),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='tipo',
            field=models.CharField(choices=[('', ''), ('L', 'L'), ('R$', 'R$')], max_length=25, verbose_name='Critério'),
        ),
    ]
