# Generated by Django 2.2.6 on 2019-10-01 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=50, verbose_name='Local')),
                ('tipo', models.CharField(blank=True, choices=[('', ''), ('banheira', 'Banheira'), ('chuveiro', 'Chuveiro'), ('filtro', 'Filtro'), ('hidromassagem', 'Hidromassagem'), ('lava-loucas', 'Lava Louças'), ('vaso-sanitario', 'Vazo Sanitário'), ('maquina-de-lavar', 'Máquina de Lavar'), ('pia', 'Pia'), ('piscina', 'Piscina'), ('ofuro', 'Ofurô'), ('outros', 'Outros')], max_length=25, null=True, verbose_name='Tipo do ponto de vazão')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Data da Captura')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='chat.Sensor')),
            ],
        ),
    ]
