# Generated by Django 2.2.6 on 2019-10-01 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Measure',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
